### ISSUE TITLE
Управление транспортом...

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Oxyd76/pyvk-t#1]
```
>> В настоящее время поддерживается прием и 
отправка сообщений, запрос
списка друзей и отображение друзей онлайн. 

Как это можно осуществить?
```

Original issue reported on code.google.com by `inf...@gmail.com` on 19 Feb 2009 at 10:05

**Comment by GoogleCodeExporter** [comment]
```
Получение списка друзей по идее должно 
быть по get roster 
или сразу get roster confirm
но у меня эта функция не работает, 
транспорт просто валится
```

Original comment by `g...@ezhika.net` on 20 Feb 2009 at 8:09

**Comment by GoogleCodeExporter** [comment]
```
у меня первый раз свалился, после get roster и 
последующего get roster confirm
после перезапуска и сразу get roster confirm - выдал 
список. но в ввиде ид, что жутко 
неудобно, да.
онлайн/оффлайн при этом не показывает
```

Original comment by `iSage....@gmail.com` on 20 Feb 2009 at 2:15

**Comment by GoogleCodeExporter** [comment]
```
а что выдал в консоль при падении?
список в виде ид должен сам клиент 
побороть, к примеру, в бомбусе есть пункт 
меню для
расстановки ников.
чтобы онлайн/оффлайн показывал, надо 
подключать вручную ("Log on" в меню по правой
кнопке в пси, "подключить" в бомбусе)
```

Original comment by `Equidamoid` on 20 Feb 2009 at 2:43
- Changed state: **Accepted**
- Added labels: **Usability**

**Comment by GoogleCodeExporter** [comment]
Original comment by `Equidamoid` on 20 Feb 2009 at 3:22

**Comment by GoogleCodeExporter** [comment]
```
больше, вроде, не падает.
клиент (psi) не борет, он, судя по всему, берет 
ник из поля nickname, а не full name
```

Original comment by `iSage....@gmail.com` on 20 Feb 2009 at 3:41

**Comment by GoogleCodeExporter** [comment]
```
у меня нормально сработало в свое время.
попробуй http://kaktyc.wordpress.com/2006/10/17/resolve-nicknames/
```

Original comment by `Equidamoid` on 20 Feb 2009 at 4:11

**Comment by GoogleCodeExporter** [comment]
```
да, помогло, спасибо. но иногда, при 
получении инфы вываливается с
Traceback (most recent call last):
  File "./pyvk-t.py", line 326, in <module>
    tr.loop(1)
  File "/usr/lib64/python2.5/site-packages/pyxmpp/jabberd/component.py", line 189, 
in loop
    self.stream.loop(timeout)
  File "/usr/lib64/python2.5/site-packages/pyxmpp/streambase.py", line 588, in loop
    act=self._loop_iter(timeout)
  File "/usr/lib64/python2.5/site-packages/pyxmpp/streambase.py", line 616, in 
_loop_iter
    self._process()
  File "/usr/lib64/python2.5/site-packages/pyxmpp/streamtls.py", line 179, in 
_process
    StreamBase._process(self)
  File "/usr/lib64/python2.5/site-packages/pyxmpp/streambase.py", line 637, in 
_process
    self._read()
  File "/usr/lib64/python2.5/site-packages/pyxmpp/streamtls.py", line 174, in _read
    StreamBase._read(self)
  File "/usr/lib64/python2.5/site-packages/pyxmpp/streambase.py", line 661, in _read
    self._feed_reader(r)
  File "/usr/lib64/python2.5/site-packages/pyxmpp/streambase.py", line 677, in 
_feed_reader
    r=self._reader.feed(data)
  File "/usr/lib64/python2.5/site-packages/pyxmpp/xmlextra.py", line 537, in feed
    return self.reader.feed(s)
  File "/usr/lib64/python2.5/site-packages/pyxmpp/xmlextra.py", line 55, in _stanza
    doc=libxml2.xmlDoc(_doc)
  File "/usr/lib64/python2.5/site-packages/libxml2.py", line 3831, in __init__
    xmlNode.__init__(self, _obj=_obj)
  File "/usr/lib64/python2.5/site-packages/pyxmpp/xmlextra.py", line 55, in _stanza
    doc=libxml2.xmlDoc(_doc)
  File "/usr/lib64/python2.5/site-packages/libxml2.py", line 3831, in __init__
    xmlNode.__init__(self, _obj=_obj)
  File "/usr/lib64/python2.5/site-packages/pyxmpp/xmlextra.py", line 55, in _stanza
    doc=libxml2.xmlDoc(_doc)
  File "/usr/lib64/python2.5/site-packages/libxml2.py", line 3831, in __init__
    xmlNode.__init__(self, _obj=_obj)
  File "/usr/lib64/python2.5/site-packages/pyxmpp/xmlextra.py", line 57, in _stanza
    self.stanza(doc,node)
  File "/usr/lib64/python2.5/site-packages/pyxmpp/streambase.py", line 401, in stanza
    self._process_node(node)
  File "/usr/lib64/python2.5/site-packages/pyxmpp/jabberd/componentstream.py", line 
195, in _process_node
    self.process_stanza(stanza)
  File "/usr/lib64/python2.5/site-packages/pyxmpp/stanzaprocessor.py", line 271, in 
process_stanza
    if self.process_iq(stanza):
  File "/usr/lib64/python2.5/site-packages/pyxmpp/stanzaprocessor.py", line 134, in 
process_iq
    response = self._iq_get_handlers[(el,ns)](stanza)
  File "./pyvk-t.py", line 189, in getVcard
    vc=self.threads[jid].getVcard(int(iq.get_from().node))
  File "/home/mahoushoujo/pyvk-t-read-only/libvkontakte.py", line 100, in getVcard
    rc=prof.find(name="div", id="rightColumn")
AttributeError: 'NoneType' object has no attribute 'find'

```

Original comment by `iSage....@gmail.com` on 20 Feb 2009 at 4:36

**Comment by GoogleCodeExporter** [comment]
```
поставил затычку от падений
похоже, у того, чью инфу ты смотрел, учетка 
от тебя закрыта
```

Original comment by `Equidamoid` on 20 Feb 2009 at 5:36

**Comment by GoogleCodeExporter** [comment]
```
м, нет, не закрыта. сейчас опробуем.
```

Original comment by `iSage....@gmail.com` on 20 Feb 2009 at 5:53

**Comment by GoogleCodeExporter** [comment]
```
теперь
Traceback (most recent call last):
  File "./pyvk-t.py", line 336, in <module>
    tr.loop(1)
  File "/usr/lib64/python2.5/site-packages/pyxmpp/jabberd/component.py", line 189, 
in loop
    self.stream.loop(timeout)
  File "/usr/lib64/python2.5/site-packages/pyxmpp/streambase.py", line 588, in loop
    act=self._loop_iter(timeout)
  File "/usr/lib64/python2.5/site-packages/pyxmpp/streambase.py", line 616, in 
_loop_iter
    self._process()
  File "/usr/lib64/python2.5/site-packages/pyxmpp/streamtls.py", line 179, in 
_process
    StreamBase._process(self)
  File "/usr/lib64/python2.5/site-packages/pyxmpp/streambase.py", line 637, in 
_process
    self._read()
  File "/usr/lib64/python2.5/site-packages/pyxmpp/streamtls.py", line 174, in _read
    StreamBase._read(self)
  File "/usr/lib64/python2.5/site-packages/pyxmpp/streambase.py", line 661, in _read
    self._feed_reader(r)
  File "/usr/lib64/python2.5/site-packages/pyxmpp/streambase.py", line 677, in 
_feed_reader
    r=self._reader.feed(data)
  File "/usr/lib64/python2.5/site-packages/pyxmpp/xmlextra.py", line 537, in feed
    return self.reader.feed(s)
  File "/usr/lib64/python2.5/site-packages/pyxmpp/xmlextra.py", line 55, in _stanza
    doc=libxml2.xmlDoc(_doc)
  File "/usr/lib64/python2.5/site-packages/libxml2.py", line 3831, in __init__
    xmlNode.__init__(self, _obj=_obj)
  File "/usr/lib64/python2.5/site-packages/pyxmpp/xmlextra.py", line 55, in _stanza
    doc=libxml2.xmlDoc(_doc)
  File "/usr/lib64/python2.5/site-packages/libxml2.py", line 3831, in __init__
    xmlNode.__init__(self, _obj=_obj)
  File "/usr/lib64/python2.5/site-packages/pyxmpp/xmlextra.py", line 55, in _stanza
    doc=libxml2.xmlDoc(_doc)
  File "/usr/lib64/python2.5/site-packages/libxml2.py", line 3831, in __init__
    xmlNode.__init__(self, _obj=_obj)
  File "/usr/lib64/python2.5/site-packages/pyxmpp/xmlextra.py", line 57, in _stanza
    self.stanza(doc,node)
  File "/usr/lib64/python2.5/site-packages/pyxmpp/streambase.py", line 401, in stanza
    self._process_node(node)
  File "/usr/lib64/python2.5/site-packages/pyxmpp/jabberd/componentstream.py", line 
195, in _process_node
    self.process_stanza(stanza)
  File "/usr/lib64/python2.5/site-packages/pyxmpp/stanzaprocessor.py", line 271, in 
process_stanza
    if self.process_iq(stanza):
  File "/usr/lib64/python2.5/site-packages/pyxmpp/stanzaprocessor.py", line 134, in 
process_iq
    response = self._iq_get_handlers[(el,ns)](stanza)
  File "./pyvk-t.py", line 190, in getVcard
    vc=self.threads[jid].getVcard(int(iq.get_from().node))
  File "/home/mahoushoujo/pyvk-t-read-only/libvkontakte.py", line 98, in getVcard
    bs=BeautifulSoup
(page,convertEntities="html",smartQuotesTo="html",fromEncoding="cp-1251")
  File "/usr/lib64/python2.5/site-packages/BeautifulSoup.py", line 1282, in __init__
    BeautifulStoneSoup.__init__(self, *args, **kwargs)
  File "/usr/lib64/python2.5/site-packages/BeautifulSoup.py", line 946, in __init__
    self._feed()
  File "/usr/lib64/python2.5/site-packages/BeautifulSoup.py", line 971, in _feed
    SGMLParser.feed(self, markup)
  File "/usr/lib64/python2.5/sgmllib.py", line 99, in feed
    self.goahead(0)
  File "/usr/lib64/python2.5/sgmllib.py", line 133, in goahead
    k = self.parse_starttag(i)
  File "/usr/lib64/python2.5/sgmllib.py", line 291, in parse_starttag
    self.finish_starttag(tag, attrs)
  File "/usr/lib64/python2.5/sgmllib.py", line 340, in finish_starttag
    self.handle_starttag(tag, method, attrs)
  File "/usr/lib64/python2.5/sgmllib.py", line 376, in handle_starttag
    method(attrs)
  File "/usr/lib64/python2.5/site-packages/BeautifulSoup.py", line 1372, in 
start_meta
    self._feed(self.declaredHTMLEncoding)
  File "/usr/lib64/python2.5/site-packages/BeautifulSoup.py", line 971, in _feed
    SGMLParser.feed(self, markup)
  File "/usr/lib64/python2.5/sgmllib.py", line 99, in feed
    self.goahead(0)
  File "/usr/lib64/python2.5/sgmllib.py", line 133, in goahead
    k = self.parse_starttag(i)
  File "/usr/lib64/python2.5/sgmllib.py", line 285, in parse_starttag
    self._convert_ref, attrvalue)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xfc in position 0: ordinal 
not 
in range(128)
```

Original comment by `iSage....@gmail.com` on 20 Feb 2009 at 6:24

**Comment by GoogleCodeExporter** [comment]
```
omfg, кодировки! 
а какой язык у вконтакта стоит?
```

Original comment by `Equidamoid` on 20 Feb 2009 at 8:24

**Comment by GoogleCodeExporter** [comment]
```
русский (ностальгический)
```

Original comment by `iSage....@gmail.com` on 21 Feb 2009 at 6:32

**Comment by GoogleCodeExporter** [comment]
```
А мне пока так и не удалось получить список 
контактов:
Traceback (most recent call last):                                              


  File "pyvk-t.py", line 336, in <module>                                           

    tr.loop(1)                                                                      

  File
"/usr/ports/net-im/py-pyxmpp/work/pyxmpp-1.0.0.664/tests/pyxmpp/jabberd/componen
t.py", line
189, in loop                                              
  File "/usr/local/lib/python2.5/site-packages/pyxmpp/streambase.py", line 588, in
loop                                                                      
    act=self._loop_iter(timeout)                                                    

  File "/usr/local/lib/python2.5/site-packages/pyxmpp/streambase.py", line 616, in
_loop_iter                                                                
    self._process()                                                                 

  File "/usr/local/lib/python2.5/site-packages/pyxmpp/streamtls.py", line 178, in
_process                                                                   
    StreamBase._process(self)                                                       

  File "/usr/local/lib/python2.5/site-packages/pyxmpp/streambase.py", line 637, in
_process                                                                  
    self._read()                                                                    

  File "/usr/local/lib/python2.5/site-packages/pyxmpp/streamtls.py", line 173, in
_read                                                                      
    StreamBase._read(self)                                                          

  File "/usr/local/lib/python2.5/site-packages/pyxmpp/streambase.py", line 661, in
_read                                                                     
    self._feed_reader(r)                                                            

  File "/usr/local/lib/python2.5/site-packages/pyxmpp/streambase.py", line 677, in
_feed_reader                                                              
    r=self._reader.feed(data)                                                       

  File "/usr/local/lib/python2.5/site-packages/pyxmpp/xmlextra.py", line 537, in feed

    return self.reader.feed(s)                                                      

  File "/usr/local/lib/python2.5/site-packages/pyxmpp/xmlextra.py", line 57, in
_stanza                                                                      
    self.stanza(doc,node)
  File "/usr/local/lib/python2.5/site-packages/pyxmpp/streambase.py", line 401, in stanza
    self._process_node(node)
  File
"/usr/ports/net-im/py-pyxmpp/work/pyxmpp-1.0.0.664/tests/pyxmpp/jabberd/componen
tstream.py",
line 195, in _process_node
  File "/usr/local/lib/python2.5/site-packages/pyxmpp/stanzaprocessor.py", line 268,
in process_stanza
    if self.process_message(stanza):
  File "/usr/local/lib/python2.5/site-packages/pyxmpp/stanzaprocessor.py", line 200,
in process_message
    if self.__try_handlers(self._message_handlers,typ,stanza):
  File "/usr/local/lib/python2.5/site-packages/pyxmpp/stanzaprocessor.py", line 179,
in __try_handlers
    response = handler(stanza)
  File "pyvk-t.py", line 151, in msgHandler
    rost=self.threads[jid].getFriendList()
  File "/usr/local/lib/jabber/pyvk/libvkontakte.py", line 192, in getFriendList
    bs=BeautifulSoup(page)
  File "/usr/local/lib/python2.5/site-packages/BeautifulSoup.py", line 1499, in __init__
    BeautifulStoneSoup.__init__(self, *args, **kwargs)
  File "/usr/local/lib/python2.5/site-packages/BeautifulSoup.py", line 1230, in __init__
    self._feed(isHTML=isHTML)
  File "/usr/local/lib/python2.5/site-packages/BeautifulSoup.py", line 1263, in _feed
    self.builder.feed(markup)
  File "/usr/local/lib/python2.5/HTMLParser.py", line 108, in feed
    self.goahead(0)
  File "/usr/local/lib/python2.5/HTMLParser.py", line 148, in goahead
    k = self.parse_starttag(i)
  File "/usr/local/lib/python2.5/HTMLParser.py", line 226, in parse_starttag
    endpos = self.check_for_whole_start_tag(i)
  File "/usr/local/lib/python2.5/HTMLParser.py", line 301, in check_for_whole_start_tag
    self.error("malformed start tag")
  File "/usr/local/lib/python2.5/HTMLParser.py", line 115, in error
    raise HTMLParseError(message, self.getpos())
HTMLParser.HTMLParseError: malformed start tag, at line 223, column 15

```

Original comment by `hart...@gmail.com` on 21 Feb 2009 at 1:34

**Comment by GoogleCodeExporter** [comment]
```
Подтверждаю актуальность вышеописанной 
проблемы:
db opened
Creating component stream: <class 
pyxmpp.jabberd.componentstream.ComponentStream at
0x28d471ac>
OUT: '<?xml version="1.0" encoding="UTF-8"?>\n<stream:stream
xmlns:stream="http://etherx.jabber.org/streams" xmlns="jabber:component:accept"
to="vkontakte.nagainos.net" version="1.0">'
StreamTLSMixIn._read(), socket: <socket._socketobject object at 0x28f808ec>
StreamBase._read(), socket: <socket._socketobject object at 0x28f808ec>
IN: '<?xml version=\'1.0\' encoding=\'UTF-8\'?><stream:stream
xmlns:stream="http://etherx.jabber.org/streams" xmlns="jabber:component:accept"
from="vkontakte.nagainos.net" id="6e78ff75">'
input document: '<?xml version="1.0" encoding="UTF-8"?>\n<stream:stream
xmlns:stream="http://etherx.jabber.org/streams" xmlns="jabber:component:accept"
from="vkontakte.nagainos.net" id="6e78ff75"/>\n'
doing handshake...
OUT: '<handshake>e2eb6acd7cb41394f5768a40d443a89bec6504d4</handshake>'
handshake hash sent.
StreamTLSMixIn._read(), socket: <socket._socketobject object at 0x28f808ec>
StreamBase._read(), socket: <socket._socketobject object at 0x28f808ec>
IN: '<handshake></handshake>'
Setting up Disco handlers...
StreamTLSMixIn._read(), socket: <socket._socketobject object at 0x28f808ec>
StreamBase._read(), socket: <socket._socketobject object at 0x28f808ec>
IN: '<iq type="get" id="142-24" from="component.nagainos.net"
to="vkontakte.nagainos.net"><query 
xmlns="http://jabber.org/protocol/disco#info"/></iq>'
Disco-info query: <iq type="get" id="142-24" from="component.nagainos.net"
to="vkontakte.nagainos.net"><query
xmlns="http://jabber.org/protocol/disco#info"/></iq> preparing response: <iq
from="vkontakte.nagainos.net" to="component.nagainos.net" type="result" 
id="142-24"/>
with reply: <query xmlns="http://jabber.org/protocol/disco#info"><identity
name="Vkontakte.ru Transport" category="x-service" type="x-unknown"/><feature
var="stringprep"/><feature var="jabber:iq:register"/><feature
var="jabber:iq:gateway"/></query>
Disco-info response: <iq from="vkontakte.nagainos.net" 
to="component.nagainos.net"
type="result" id="142-24"><query
xmlns="http://jabber.org/protocol/disco#info"><identity name="Vkontakte.ru 
Transport"
category="x-service" type="x-unknown"/><feature var="stringprep"/><feature
var="jabber:iq:register"/><feature var="jabber:iq:gateway"/></query></iq>
OUT: '<iq from="vkontakte.nagainos.net" to="component.nagainos.net" 
type="result"
id="142-24"><query xmlns="http://jabber.org/protocol/disco#info"><identity
name="Vkontakte.ru Transport" category="x-service" type="x-unknown"/><feature
var="stringprep"/><feature var="jabber:iq:register"/><feature
var="jabber:iq:gateway"/></query></iq>'
StreamTLSMixIn._read(), socket: <socket._socketobject object at 0x28f808ec>
StreamBase._read(), socket: <socket._socketobject object at 0x28f808ec>
IN: '<presence type="unavailable" to="vkontakte.nagainos.net"
from="nagainos@nagainos.net/Jugernaut"/>'
u'unavailable'
OUT: '<presence from="vkontakte.nagainos.net" 
to="nagainos@nagainos.net/Jugernaut"
type="unavailable"/>'
StreamTLSMixIn._read(), socket: <socket._socketobject object at 0x28f808ec>
StreamBase._read(), socket: <socket._socketobject object at 0x28f808ec>
IN: '<presence to="vkontakte.nagainos.net"
from="nagainos@nagainos.net/Jugernaut">\n<priority>5</priority>\n<c
xmlns="http://jabber.org/protocol/caps" node="http://psi-im.org/caps" ver="0.12"
ext="cs ep-notify html"/>\n<x
xmlns="vcard-temp:x:update">\n<photo>7be3650abd7ab46aec4e53f1a960e37cf247dfc7</p
hoto>\n</x>\n</presence>'
None
OUT: '<presence from="vkontakte.nagainos.net" 
to="nagainos@nagainos.net/Jugernaut"/>'
OUT: '<presence  from="vkontakte.nagainos.net"
to="nagainos@nagainos.net"><show>away</show><status>logging 
in...</status></presence>'
OUT: '<presence from="vkontakte.nagainos.net" to="nagainos@nagainos.net"/>'
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python2.5/threading.py", line 486, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.5/threading.py", line 446, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/home/Freeman/pyvk-t-read-only/libvkontakte.py", line 212, in loop
    tonline=self.getOnlineList()
  File "/usr/home/Freeman/pyvk-t-read-only/libvkontakte.py", line 73, in getOnlineList
    bs=BeautifulSoup(page)
  File "/usr/local/lib/python2.5/site-packages/BeautifulSoup.py", line 1499, in __init__
    BeautifulStoneSoup.__init__(self, *args, **kwargs)
  File "/usr/local/lib/python2.5/site-packages/BeautifulSoup.py", line 1230, in __init__
    self._feed(isHTML=isHTML)
  File "/usr/local/lib/python2.5/site-packages/BeautifulSoup.py", line 1263, in _feed
    self.builder.feed(markup)
  File "/usr/local/lib/python2.5/HTMLParser.py", line 108, in feed
    self.goahead(0)
  File "/usr/local/lib/python2.5/HTMLParser.py", line 148, in goahead
    k = self.parse_starttag(i)
  File "/usr/local/lib/python2.5/HTMLParser.py", line 226, in parse_starttag
    endpos = self.check_for_whole_start_tag(i)
  File "/usr/local/lib/python2.5/HTMLParser.py", line 301, in check_for_whole_start_tag
    self.error("malformed start tag")
  File "/usr/local/lib/python2.5/HTMLParser.py", line 115, in error
    raise HTMLParseError(message, self.getpos())
HTMLParseError: malformed start tag, at line 195, column 15

StreamTLSMixIn._read(), socket: <socket._socketobject object at 0x28f808ec>
StreamBase._read(), socket: <socket._socketobject object at 0x28f808ec>
IN: '<message type="chat" to="vkontakte.nagainos.net" id="aee4a"
from="nagainos@nagainos.net/Jugernaut">\n<body>get roster 
confirm</body>\n<active
xmlns="http://jabber.org/protocol/chatstates"/>\n</message>'
Traceback (most recent call last):
  File "./pyvk-t.py", line 337, in <module>
    tr.loop(1)
  File
"/usr/ports/net-im/py-pyxmpp/work/pyxmpp-1.0.0.664/tests/pyxmpp/jabberd/componen
t.py",
line 189, in loop
  File "/usr/local/lib/python2.5/site-packages/pyxmpp/streambase.py", line 588, in loop
    act=self._loop_iter(timeout)
  File "/usr/local/lib/python2.5/site-packages/pyxmpp/streambase.py", line 616, in
_loop_iter
    self._process()
  File "/usr/local/lib/python2.5/site-packages/pyxmpp/streamtls.py", line 178, in
_process
    StreamBase._process(self)
  File "/usr/local/lib/python2.5/site-packages/pyxmpp/streambase.py", line 637, in
_process
    self._read()
  File "/usr/local/lib/python2.5/site-packages/pyxmpp/streamtls.py", line 173, in _read
    StreamBase._read(self)
  File "/usr/local/lib/python2.5/site-packages/pyxmpp/streambase.py", line 661, in _read
    self._feed_reader(r)
  File "/usr/local/lib/python2.5/site-packages/pyxmpp/streambase.py", line 677, in
_feed_reader
    r=self._reader.feed(data)
  File "/usr/local/lib/python2.5/site-packages/pyxmpp/xmlextra.py", line 537, in feed
    return self.reader.feed(s)
  File "/usr/local/lib/python2.5/site-packages/pyxmpp/xmlextra.py", line 57, in _stanza
    self.stanza(doc,node)
  File "/usr/local/lib/python2.5/site-packages/pyxmpp/streambase.py", line 401, in stanza
    self._process_node(node)
  File
"/usr/ports/net-im/py-pyxmpp/work/pyxmpp-1.0.0.664/tests/pyxmpp/jabberd/componen
tstream.py",
line 195, in _process_node
  File "/usr/local/lib/python2.5/site-packages/pyxmpp/stanzaprocessor.py", line 268,
in process_stanza
    if self.process_message(stanza):
  File "/usr/local/lib/python2.5/site-packages/pyxmpp/stanzaprocessor.py", line 200,
in process_message
    if self.__try_handlers(self._message_handlers,typ,stanza):
  File "/usr/local/lib/python2.5/site-packages/pyxmpp/stanzaprocessor.py", line 179,
in __try_handlers
    response = handler(stanza)
  File "./pyvk-t.py", line 152, in msgHandler
    rost=self.threads[jid].getFriendList()
  File "/usr/home/Freeman/pyvk-t-read-only/libvkontakte.py", line 192, in getFriendList
    bs=BeautifulSoup(page)
  File "/usr/local/lib/python2.5/site-packages/BeautifulSoup.py", line 1499, in __init__
    BeautifulStoneSoup.__init__(self, *args, **kwargs)
  File "/usr/local/lib/python2.5/site-packages/BeautifulSoup.py", line 1230, in __init__
    self._feed(isHTML=isHTML)
  File "/usr/local/lib/python2.5/site-packages/BeautifulSoup.py", line 1263, in _feed
    self.builder.feed(markup)
  File "/usr/local/lib/python2.5/HTMLParser.py", line 108, in feed
    self.goahead(0)
  File "/usr/local/lib/python2.5/HTMLParser.py", line 148, in goahead
    k = self.parse_starttag(i)
  File "/usr/local/lib/python2.5/HTMLParser.py", line 226, in parse_starttag
    endpos = self.check_for_whole_start_tag(i)
  File "/usr/local/lib/python2.5/HTMLParser.py", line 301, in check_for_whole_start_tag
    self.error("malformed start tag")
  File "/usr/local/lib/python2.5/HTMLParser.py", line 115, in error
    raise HTMLParseError(message, self.getpos())
HTMLParser.HTMLParseError: malformed start tag, at line 195, column 15

```

Original comment by `free...@tis-dialog.ru` on 21 Feb 2009 at 3:25

**Comment by GoogleCodeExporter** [comment]
```
без кода странички ничего сказать не могу.
в 8 ревизии добавил сохранение страницы, 
вызвавшей сбой, в файл pagedump.html и
перехват исключения.
попробуй обновиться и запросить еще раз.
если не получится, выложи сюда ту строчку, 
на которую он ругнется
```

Original comment by `Equidamoid` on 21 Feb 2009 at 5:25
- Added labels: **Priority-High**
- Removed labels: **Priority-Medium**

**Comment by GoogleCodeExporter** [comment]
```
Страничка не создалась...
я ведь так понимаю, что она должна была 
появиться в папке с транспортом...

StreamTLSMixIn._read(), socket: <socket._socketobject object at 0x29021fb4>
StreamBase._read(), socket: <socket._socketobject object at 0x29021fb4>    
IN: "<message from='hartois@hartois.info/Gajim' to='vkontakte.hartois.info'
xml:lang='ru' type='chat' id='188'><body>get roster confirm</body><request
xmlns='urn:xmpp:receipts'/><thread>omCzGUSsOKLSxFcXFbHHTezlCHeawfPk</thread></me
ssage>"

Traceback (most recent call last):                                              


  File "pyvk-t.py", line 336, in <module>                                           

    tr.loop(1)                                                                      

  File
"/usr/ports/net-im/py-pyxmpp/work/pyxmpp-1.0.0.664/tests/pyxmpp/jabberd/componen
t.py", line
189, in loop                                              
  File "/usr/local/lib/python2.5/site-packages/pyxmpp/streambase.py", line 588, in
loop                                                                      
    act=self._loop_iter(timeout)                                                    

  File "/usr/local/lib/python2.5/site-packages/pyxmpp/streambase.py", line 616, in
_loop_iter                                                                
    self._process()                                                                 

  File "/usr/local/lib/python2.5/site-packages/pyxmpp/streamtls.py", line 178, in
_process
    StreamBase._process(self)
  File "/usr/local/lib/python2.5/site-packages/pyxmpp/streambase.py", line 637, in
_process
    self._read()
  File "/usr/local/lib/python2.5/site-packages/pyxmpp/streamtls.py", line 173, in _read
    StreamBase._read(self)
  File "/usr/local/lib/python2.5/site-packages/pyxmpp/streambase.py", line 661, in _read
    self._feed_reader(r)
  File "/usr/local/lib/python2.5/site-packages/pyxmpp/streambase.py", line 677, in
_feed_reader
    r=self._reader.feed(data)
  File "/usr/local/lib/python2.5/site-packages/pyxmpp/xmlextra.py", line 537, in feed
    return self.reader.feed(s)
  File "/usr/local/lib/python2.5/site-packages/pyxmpp/xmlextra.py", line 57, in _stanza
    self.stanza(doc,node)
  File "/usr/local/lib/python2.5/site-packages/pyxmpp/streambase.py", line 401, in stanza
    self._process_node(node)
  File
"/usr/ports/net-im/py-pyxmpp/work/pyxmpp-1.0.0.664/tests/pyxmpp/jabberd/componen
tstream.py",
line 195, in _process_node
  File "/usr/local/lib/python2.5/site-packages/pyxmpp/stanzaprocessor.py", line 268,
in process_stanza
    if self.process_message(stanza):
  File "/usr/local/lib/python2.5/site-packages/pyxmpp/stanzaprocessor.py", line 200,
in process_message
    if self.__try_handlers(self._message_handlers,typ,stanza):
  File "/usr/local/lib/python2.5/site-packages/pyxmpp/stanzaprocessor.py", line 179,
in __try_handlers
    response = handler(stanza)
  File "pyvk-t.py", line 151, in msgHandler
    rost=self.threads[jid].getFriendList()
  File "/usr/local/lib/jabber/pyvk/libvkontakte.py", line 204, in getFriendList
    except Excepion,ex:
NameError: global name 'Excepion' is not defined

```

Original comment by `hart...@gmail.com` on 21 Feb 2009 at 5:56

**Comment by GoogleCodeExporter** [comment]
```
упс, опечатка, в 8й поправил :-[
```

Original comment by `Equidamoid` on 21 Feb 2009 at 6:20

**Comment by GoogleCodeExporter** [comment]
```
ну, вроде, со списком проблем не 
наблюдается больше
[fixed]
```

Original comment by `Equidamoid` on 22 Feb 2009 at 2:43
- Changed state: **Fixed**
