### ISSUE TITLE
Неверный email и/или пароль.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Oxyd76/pyvk-t#107]
```
Говорит сабж.

```

Original issue reported on code.google.com by `krivun.a...@gmail.com` on 16 Sep 2011 at 3:38

**Comment by GoogleCodeExporter** [comment]
```
Вот чего в логе  

* 2011-09-16 19:47:05,283 [WAR]         loop @ UL3 (NULL):   no matching queues!
    * 2011-09-16 19:47:05,284 [WAR]    applyData @ UL4 (krivun@****):  no api auth data
    * 2011-09-16 19:47:05,284 [WAR] readDataMongo @ UL4 (krivun@****):         mongo ok
    * 2011-09-16 19:47:05,328 [WAR]         loop @ AsyncoreLooper:       entering asyncore loop
    * 2011-09-16 19:47:05,328 [WAR]         loop @ AsyncoreLooper:       asyncore loop exitted
    * 2011-09-16 19:47:05,613 [WAR]   hdrHandler @ UL4 (krivun@****):  got Location header 'http://vkontakte.ru/login.php?act=slogin&fast=1&hash=5ec0f70244a58d2ffb2a48c040052e6f&redirect=1&s=1' [http://login.vk.com/?act=login] 
    * 2011-09-16 19:47:05,613 [ERR]   hdrHandler @ UL4 (krivun@****):  
Traceback (most recent call last):
  File "/usr/lib/pyvk-t/pyvkt/libvkontakte.py", line 332, in hdrHandler
    raise HTTPError("Redirect", url)
HTTPError: Redirect [http://login.vk.com/?act=login]
Traceback (most recent call last):
  File "/usr/lib/pyvk-t/pyvkt/libvkontakte.py", line 332, in hdrHandler
    raise HTTPError("Redirect", url)
pyvkt.libvkontakte.HTTPError: Redirect [http://login.vk.com/?act=login]
    * 2011-09-16 19:47:05,614 [WAR]  getHttpPage @ UL4 (krivun@****):  redirect?
    * 2011-09-16 19:47:05,614 [WAR]  getHttpPage @ UL4 (krivun@****):  http://vkontakte.ru/login.php?act=slogin&fast=1&hash=5ec0f70244a58d2ffb2a48c040052e6f&redirect=1&s=1

    * 2011-09-16 19:47:05,634 [WAR]   dumpString @ UL4 (krivun@****):  parser error: page saved to ./dumps/redirect-1316188025
    * 2011-09-16 19:47:05,687 [WAR]   hdrHandler @ UL4 (krivun@****):  got Location header 'https://login.vk.com/?fast=1&from_host=vkontakte.ru&from_protocol=http&ip_h=180f1a617eca30c7c9&to=bG9naW4ucGhwP29wPXNsb2dpbiZyZWRpcmVjdD0xJnRvPSZyZXF1ZXN0X21ldGhvZD1wb3N0' [http://vkontakte.ru/login.php?op=slogin&redirect=1&to=&request_method=post] 
    * 2011-09-16 19:47:05,687 [ERR]   hdrHandler @ UL4 (krivun@****):  
Traceback (most recent call last):
  File "/usr/lib/pyvk-t/pyvkt/libvkontakte.py", line 332, in hdrHandler
    raise HTTPError("Redirect", url)
HTTPError: Redirect 
[http://vkontakte.ru/login.php?op=slogin&redirect=1&to=&request_method=post]
Traceback (most recent call last):
  File "/usr/lib/pyvk-t/pyvkt/libvkontakte.py", line 332, in hdrHandler
    raise HTTPError("Redirect", url)
pyvkt.libvkontakte.HTTPError: Redirect 
[http://vkontakte.ru/login.php?op=slogin&redirect=1&to=&request_method=post]
    * 2011-09-16 19:47:05,688 [WAR]  getHttpPage @ UL4 (krivun@****):  redirect?
    * 2011-09-16 19:47:05,688 [WAR]  getHttpPage @ UL4 (krivun@****):  https://login.vk.com/?fast=1&from_host=vkontakte.ru&from_protocol=http&ip_h=180f1a617eca30c7c9&to=bG9naW4ucGhwP29wPXNsb2dpbiZyZWRpcmVjdD0xJnRvPSZyZXF1ZXN0X21ldGhvZD1wb3N0

    * 2011-09-16 19:47:05,741 [WAR]   dumpString @ UL4 (krivun@****):  parser error: page saved to ./dumps/redirect-1316188025
    * 2011-09-16 19:47:05,820 [WAR] createThread @ UL4 (krivun@****):  authError
    * 2011-09-16 19:47:06,284 [WAR]         loop @ UL3 (NULL):   no matching queues!
    * 2011-09-16 19:47:06,329 [WAR]         loop @ AsyncoreLooper:       entering asyncore loop
    * 2011-09-16 19:47:06,329 [WAR]         loop @ AsyncoreLooper:       asyncore loop exitted
    * 2011-09-16 19:47:07,285 [WAR]         loop @ UL3 (NULL):   no matching queues!
    * 2011-09-16 19:47:07,329 [WAR]         loop @ AsyncoreLooper:       entering asyncore loop
    * 2011-09-16 19:47:07,330 [WAR]         loop @ AsyncoreLooper:       asyncore loop exitted

```

Original comment by `krivun.a...@gmail.com` on 16 Sep 2011 at 3:49

**Comment by GoogleCodeExporter** [comment]
```
А в dumps/redirect-xxxxx падает кусок веба "400 bad request"
```

Original comment by `krivun.a...@gmail.com` on 19 Sep 2011 at 1:30
