### ISSUE TITLE
Не отображается список онлайн

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Oxyd76/pyvk-t#2]
```

Exception in thread Thread-5:
Traceback (most recent call last):
  File "threading.py", line 442, in __bootstrap
    self.run()
  File "threading.py", line 422, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/pyvk-t/libvkontakte.py", line 203, in loop
    tonline=self.getOnlineList()
  File "/opt/pyvk-t/libvkontakte.py", line 78, in getOnlineList
    a=demjson.decode(trgScr)
  File "/usr/lib/python2.4/site-packages/demjson.py", line 2135, in decode
    obj = j.decode( unitxt )
  File "/usr/lib/python2.4/site-packages/demjson.py", line 1706, in decode
    r = self.decodeobj(txt, 0, only_object_or_array=not
self._allow_any_type_at_start)
  File "/usr/lib/python2.4/site-packages/demjson.py", line 1695, in decodeobj
    raise JSONDecodeError('unknown keyword or identifier',kw)
JSONDecodeError: ('unknown keyword or identifier', u'ndSubmit')



```

Original issue reported on code.google.com by `gennady....@gmail.com` on 20 Feb 2009 at 6:39

**Comment by GoogleCodeExporter** [comment]
```
Кое-что подправил, теперь не будет от этого 
падать и выдаст что-то более внятное в
консоль.
Обнови до последней ревизии и попробуй еще 
раз
```

Original comment by `Equidamoid` on 20 Feb 2009 at 3:22
- Changed state: **Started**

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
Жду подтверждения
```

Original comment by `Equidamoid` on 22 Feb 2009 at 6:27
- Changed state: **Unconfirmed**
- Added labels: **Priority-Low**
- Removed labels: **Priority-High**

**Comment by GoogleCodeExporter** [comment]
```
Подтверждаю. Проблема решилась!
```

Original comment by `gennady....@gmail.com` on 25 Feb 2009 at 9:46

**Comment by GoogleCodeExporter** [comment]
Original comment by `Equidamoid` on 27 Feb 2009 at 4:50
- Changed state: **Fixed**
