### ISSUE TITLE
Failed to load application: No section: 'general'

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Oxyd76/pyvk-t#23]
```
При запуске выдаёт эту ошибку и в лог пишет 
это:
2009/03/16 22:22 +0400 [-]   File
"/home/firestarter/Desktop/Install/pyvk-t/pyvkt_new.tac", line 18, in <module>
2009/03/16 22:22 +0400 [-]    
srvAddr="tcp:%s:%s"%(config.get("general","server"),config.getint("general","por
t"))
2009/03/16 22:22 +0400 [-]   File "/usr/lib/python2.5/ConfigParser.py",
line 511, in get
2009/03/16 22:22 +0400 [-]     raise NoSectionError(section)
2009/03/16 22:22 +0400 [-] NoSectionError: No section: 'general'
2009/03/16 22:22 +0400 [-] Failed to load application: No section: 'general'
2009/03/16 22:22 +0400 [-] Unhandled Error
    Traceback (most recent call last):
      File "/usr/lib/python2.5/site-packages/twisted/application/app.py", line
379, in run
        runApp(config)
      File "/usr/lib/python2.5/site-packages/twisted/scripts/twistd.py", line
23, in runApp
        _SomeApplicationRunner(config).run()
      File "/usr/lib/python2.5/site-packages/twisted/application/app.py", line
157, in run
        self.application = self.createOrGetApplication()
      File "/usr/lib/python2.5/site-packages/twisted/application/app.py", line
207, in createOrGetApplication
        application = getApplication(self.config, passphrase)
    --- <exception caught here> ---
      File "/usr/lib/python2.5/site-packages/twisted/application/app.py", line
218, in getApplication
        application = service.loadApplication(filename, style, passphrase)
      File "/usr/lib/python2.5/site-packages/twisted/application/service.py",
line 341, in loadApplication
        application = sob.loadValueFromFile(filename, 'application', passphrase)
      File "/usr/lib/python2.5/site-packages/twisted/persisted/sob.py", line
215, in loadValueFromFile
        exec fileObj in d, d
      File "/home/firestarter/Desktop/Install/pyvk-t/pyvkt_new.tac", line 18,
in <module>

srvAddr="tcp:%s:%s"%(config.get("general","server"),config.getint("general","por
t"))
      File "/usr/lib/python2.5/ConfigParser.py", line 511, in get
        raise NoSectionError(section)
    ConfigParser.NoSectionError: No section: 'general'

2009/03/16 22:22 +0400 [-] 

```

Original issue reported on code.google.com by `retratserif@gmail.com` on 16 Mar 2009 at 6:40

**Comment by GoogleCodeExporter** [comment]
```
Извините, разобрался, оказывается нужно 
запускать из директории где расположен
pyvk-t_new.cfg
```

Original comment by `retratserif@gmail.com` on 16 Mar 2009 at 7:04

**Comment by GoogleCodeExporter** [comment]
Original comment by `tishka17` on 17 Mar 2009 at 5:59
- Changed state: **Unconfirmed**

**Comment by GoogleCodeExporter** [comment]
```
можно еще указывать путь к конфигу через 
переменную окружения PYVKT_CONFIG
```

Original comment by `Equidamoid` on 25 Mar 2009 at 5:07
- Changed state: **Invalid**
