### ISSUE TITLE
Status sync

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Oxyd76/pyvk-t#26]
```

2009-03-17 18:32:14+0000 [XmlStream,client] Unhandled Error
        Traceback (most recent call last):
          File "/usr/lib/python2.5/threading.py", line 462, in __bootstrap
            self.__bootstrap_inner()
          File "/usr/lib/python2.5/threading.py", line 486, in 
__bootstrap_inner
            self.run()
          File "/usr/lib/python2.5/threading.py", line 446, in run
            self.__target(*self.__args, **self.__kwargs)
        --- <exception caught here> ---
          File "/usr/lib/python2.5/site-packages/twisted/python/
threadpool.py", line 161, in _worker
            context.call(ctx, function, *args, **kwargs)
          File "/usr/lib/python2.5/site-packages/twisted/python/
context.py", line 59, in callWithContext
            return self.currentContext().callWithContext(ctx, func, *args, 
**kw)
          File "/usr/lib/python2.5/site-packages/twisted/python/
context.py", line 37, in callWithContext
            return func(*args,**kw)
          File "/home/xmpp-t/vkontakte/pyvkt_new.py", line 735, in 
updateStatus
            if self.threads.has_key(bjid) and self.sync_status:
        exceptions.NameError: global name 'self' is not defined
```

Original issue reported on code.google.com by `zdevel` on 17 Mar 2009 at 6:32

**Comment by GoogleCodeExporter** [comment]
```
Статус при этом не обновляется разумеется
```

Original comment by `zdevel` on 17 Mar 2009 at 6:37

**Comment by GoogleCodeExporter** [comment]
Original comment by `tishka17` on 17 Mar 2009 at 7:00
- Changed state: **Started**

**Comment by GoogleCodeExporter** [comment]
Original comment by `tishka17` on 17 Mar 2009 at 7:50
- Changed state: **Fixed**
