### ISSUE TITLE
Ошибки при старте 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Oxyd76/pyvk-t#27]
```
После обновления стало выскакивать вот 
такое
[xmpp-t@bsrv:~/vkontakte]% ./start.sh
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/twisted/python/usage.py", line 
373, in <lambda>
    fn = lambda name, value, m=method: m(value)
  File "/usr/lib/python2.5/site-packages/twisted/application/app.py", line 
488, in opt_reactor
    installReactor(shortName)
  File "/usr/lib/python2.5/site-packages/twisted/application/reactors.py", 
line 79, in installReactor
    for installer in getReactorTypes():
  File "/usr/lib/python2.5/site-packages/twisted/plugin.py", line 200, in 
getPlugins
    allDropins = getCache(package)
--- <exception caught here> ---
  File "/usr/lib/python2.5/site-packages/twisted/plugin.py", line 179, in 
getCache
    dropinPath.setContent(pickle.dumps(dropinDotCache))
  File "/usr/lib/python2.5/site-packages/twisted/python/filepath.py", line 
574, in setContent
    sib.open('w').write(content)
  File "/usr/lib/python2.5/site-packages/twisted/python/filepath.py", line 
384, in open
    return open(self.path, mode+'b')
exceptions.IOError: [Errno 13] Permission denied: '/usr/lib/python2.5/site-
packages/twisted/plugins/dropin.cache.new'
Removing stale pidfile /home/xmpp-t/vkontakte/twistd.pid

```

Original issue reported on code.google.com by `zdevel` on 18 Mar 2009 at 10:07

**Comment by GoogleCodeExporter** [comment]
```
Процесс, правда, при этом успешно 
запускается.
```

Original comment by `zdevel` on 18 Mar 2009 at 10:07

**Comment by GoogleCodeExporter** [comment]
```
chmod 777 на папочку plugins. Не секьюрный вариант, 
но на сервере кроме меня никого 
нет, так что пох. И все, никаких ворнингов.
```

Original comment by `zdevel` on 19 Mar 2009 at 4:14

**Comment by GoogleCodeExporter** [comment]
```
похоже, что-то связанное с дистром, у меня 
от обычного юзера нормально запускается.

777?? О_о не надо!
```

Original comment by `Equidamoid` on 22 Mar 2009 at 8:31

**Comment by GoogleCodeExporter** [comment]
Original comment by `Equidamoid` on 16 Oct 2009 at 3:24
- Changed state: **Unconfirmed**
- Added labels: **Priority-Low**
- Removed labels: **Priority-Medium**
