### ISSUE TITLE
Не стартует

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Oxyd76/pyvk-t#34]
```
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/twisted/application/app.py", line 
614, in run
    runApp(config)
  File "/usr/lib/python2.5/site-packages/twisted/scripts/twistd.py", line 
23, in runApp
    _SomeApplicationRunner(config).run()
  File "/usr/lib/python2.5/site-packages/twisted/application/app.py", line 
330, in run
    self.application = self.createOrGetApplication()
  File "/usr/lib/python2.5/site-packages/twisted/application/app.py", line 
416, in createOrGetApplication
    application = getApplication(self.config, passphrase)
--- <exception caught here> ---
  File "/usr/lib/python2.5/site-packages/twisted/application/app.py", line 
427, in getApplication
    application = service.loadApplication(filename, style, passphrase)
  File "/usr/lib/python2.5/site-packages/twisted/application/service.py", 
line 368, in loadApplication
    application = sob.loadValueFromFile(filename, 'application', 
passphrase)
  File "/usr/lib/python2.5/site-packages/twisted/persisted/sob.py", line 
214, in loadValueFromFile
    exec fileObj in d, d
  File "pyvkt_new.tac", line 6, in <module>
    import pyvkt_new
  File "/home/xmpp-t/vkontakte/pyvkt_new.py", line 28, in <module>
    from pyvkt_user import user
exceptions.SyntaxError: invalid syntax (pyvkt_user.py, line 45)

Failed to load application: invalid syntax (pyvkt_user.py, line 45)

(r79)
```

Original issue reported on code.google.com by `zdevel` on 21 Mar 2009 at 12:54

**Comment by GoogleCodeExporter** [comment]
```
уже исправлено
```

Original comment by `Equidamoid` on 22 Mar 2009 at 8:25
- Changed state: **Fixed**
