### ISSUE TITLE
Ошибка

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Oxyd76/pyvk-t#39]
```
Хз что это. Появилось после суток висения 
транспорта в онлайне. После этого
подключаться не захотел. Убивался только 
через -9.
Тут полученное сообщение еще, перед 
падением примерно.
2009-03-28 04:01:15+0000 [-] this in NOT an ERROR!
2009-03-28 04:01:15+0000 [-]   File "/home/xmpp-t/vkontakte/pyvkt_new.py",
line 717, in updateFeed
2009-03-28 04:01:15+0000 [-]    
self.users[jid].pool.callInThread(self.requestMessage,jid=jid,msgid=i)
2009-03-28 04:01:15+0000 [-]   File
"/home/xmpp-t/vkontakte/pyvkt_spikes.py", line 27, in callInThread
2009-03-28 04:01:15+0000 [-]     print_stack(limit=2)
2009-03-28 04:01:15+0000 [-] msg request
2009-03-28 04:01:15+0000 [-] {'date': u'at  7:01 a.m. on Mar 28, 2009',
'text': u'\u043c\u0435\u0441\u0442\u0430 \u0435\u0449\u0451
\u0435\u0441\u0442\u044c?', 'from': u'7438233', 'title':
u'\u0442\u0435\u0441\u0442
\u0442\u0440\u0430\u043d\u0441\u043f\u043e\u0440\u0442\u043e\u0432'}
2009-03-28 04:01:15+0000 [-] waiting for task
2009-03-28 05:10:36+0000 [XmlStream,client] legacy message
2009-03-28 05:10:36+0000 [XmlStream,client] deprecated callInThread
2009-03-28 05:10:36+0000 [XmlStream,client] this in NOT an ERROR!
2009-03-28 05:10:36+0000 [XmlStream,client]   File
"/home/xmpp-t/vkontakte/pyvkt_new.py", line 231, in onMessage
2009-03-28 05:10:36+0000 [XmlStream,client]    
self.users[bjid].pool.callInThread(self.submitMessage,jid=bjid,v_id=v_id,body=bo
dy,title=title)
2009-03-28 05:10:36+0000 [XmlStream,client]   File
"/home/xmpp-t/vkontakte/pyvkt_spikes.py", line 27, in callInThread
2009-03-28 05:10:36+0000 [XmlStream,client]     print_stack(limit=2)
2009-03-28 05:10:36+0000 [-] message delivered
2009-03-28 05:10:36+0000 [-] waiting for task
2009-03-28 06:48:20+0000 [XmlStream,client] updating status for
x-demon@x-demon.org : 
2009-03-28 06:54:22+0000 [XmlStream,client] logout x-demon@x-demon.org
2009-03-28 06:54:22+0000 [XmlStream,client] adbapi closing: MySQLdb
2009-03-28 06:54:22+0000 [XmlStream,client] Connection lost.
2009-03-28 06:54:22+0000 [XmlStream,client] logout
2009-03-28 06:54:22+0000 [XmlStream,client] delThread x-demon@x-demon.org
2009-03-28 06:54:41+0000 [XmlStream,client] SELECT * FROM users WHERE
jid='x-demon@x-demon.org'
2009-03-28 06:54:41+0000 [XmlStream,client] adbapi closing: MySQLdb
2009-03-28 06:54:41+0000 [XmlStream,client] Connection lost.
2009-03-28 07:08:33+0000 [XmlStream,client] x-demon@x-demon.org 0
2009-03-28 07:08:35+0000 [XmlStream,client] Unhandled Error
    Traceback (most recent call last):
      File "/home/packages/python/2.5/python2.5-2.5.2/Modules/pyexpat.c", line
656, in EndElement

      File "/usr/lib/python2.5/site-packages/twisted/words/xish/domish.py",
line 780, in _onEndElement
        self.ElementEvent(self.currElem)
      File "/usr/lib/python2.5/site-packages/twisted/words/xish/xmlstream.py",
line 106, in onElement
        self.dispatch(element)
      File "/usr/lib/python2.5/site-packages/twisted/words/xish/utility.py",
line 316, in dispatch
        callbacklist.callback(obj)
    --- <exception caught here> ---
      File "/usr/lib/python2.5/site-packages/twisted/words/xish/utility.py",
line 106, in callback
        methodwrapper(*args, **kwargs)
      File "/usr/lib/python2.5/site-packages/twisted/words/xish/utility.py",
line 27, in __call__
        self.method(*nargs, **nkwargs)
      File "/home/xmpp-t/vkontakte/pyvkt_new.py", line 422, in onIq

d=deferToThreadPool(reactor,self.users[bjid].pool,f=self.commands.onIqSet,iq=iq)
    exceptions.AttributeError: user instance has no attribute 'pool'

```

Original issue reported on code.google.com by `zdevel` on 28 Mar 2009 at 7:12

**Comment by GoogleCodeExporter** [comment]
```
похоже, проблема с отключением юзера..
а до того threadError'ы не возникали, случаем?
```

Original comment by `Equidamoid` on 28 Mar 2009 at 7:50

**Comment by GoogleCodeExporter** [comment]
```
2009/03/29 21:29 +0400 [XmlStream,client] Unhandled Error
    Traceback (most recent call last):
      File "/usr/lib/python2.5/site-packages/twisted/python/log.py", line 48, in
callWithLogger
        return callWithContext({"system": lp}, func, *args, **kw)
      File "/usr/lib/python2.5/site-packages/twisted/python/log.py", line 33, in
callWithContext
        return context.call({ILogContext: newCtx}, func, *args, **kw)
      File "/usr/lib/python2.5/site-packages/twisted/python/context.py", line 59, in
callWithContext
        return self.currentContext().callWithContext(ctx, func, *args, **kw)
      File "/usr/lib/python2.5/site-packages/twisted/python/context.py", line 37, in
callWithContext
        return func(*args,**kw)
    --- <exception caught here> ---
      File "/usr/lib/python2.5/site-packages/twisted/internet/epollreactor.py", line
197, in _doReadOrWrite
        why = selectable.doRead()
      File "/usr/lib/python2.5/site-packages/twisted/internet/tcp.py", line 362, in doRead
        return self.protocol.dataReceived(data)
      File "/usr/lib/python2.5/site-packages/twisted/words/xish/xmlstream.py", line 72,
in dataReceived
        self.stream.parse(data)
      File "/usr/lib/python2.5/site-packages/twisted/words/xish/domish.py", line 730, in
parse
        self.parser.Parse(buffer)
      File "/usr/lib/python2.5/site-packages/twisted/words/xish/domish.py", line 771, in
_onEndElement
        self.ElementEvent(self.currElem)
      File "/usr/lib/python2.5/site-packages/twisted/words/xish/xmlstream.py", line 104,
in onElement
        self.dispatch(element)
      File "/usr/lib/python2.5/site-packages/twisted/words/xish/utility.py", line 233,
in dispatch
        callbacklist.callback(object)
      File "/usr/lib/python2.5/site-packages/twisted/words/xish/utility.py", line 37, in
callback
        methodwrapper(*args, **kwargs)
      File "/usr/lib/python2.5/site-packages/twisted/words/xish/utility.py", line 21, in
__call__
        self.method(*nargs, **nkwargs)
      File "/home/firestarter/Desktop/Files/New/Install/pyvk-t/pyvkt_new.py", line 286,
in onIq
        self.xmlstream.send(self.commands.onDiscoInfo(iq))
      File "/home/firestarter/Desktop/Files/New/Install/pyvk-t/pyvkt_commands.py", line
158, in onDiscoInfo
        resp=xmlstream.toResponse(iq)
    exceptions.AttributeError: 'module' object has no attribute 'toResponse'

2009/03/29 21:29 +0400 [XmlStream,client] Unhandled error in Deferred:
2009/03/29 21:29 +0400 [XmlStream,client] Unhandled Error
    Traceback (most recent call last):
    Failure: twisted.internet.error.ConnectionLost: Connection to the other side was
lost in a non-clean fashion.

Завёл два аккаунта вконтакте, 
зарегистрировал транспорт на разных JID'ах, 
пробовал
общаться друг с другом. Сообщения приходят 
только одному.
А ещё статус пользователей всегда off.
```

Original comment by `retratserif@gmail.com` on 29 Mar 2009 at 5:44

**Comment by GoogleCodeExporter** [comment]
```
retratserif, какая версия twisted? нужна 8.1.0 минимум
Кстати, у свеже зарегистрированных могу 
часто вылезать капчи и поэтому сообщения 
не 
уходить
```

Original comment by `tishka17` on 2 Apr 2009 at 3:50

**Comment by GoogleCodeExporter** [comment]
```
Да, у меня 2.5.0 оказывается (такая версия в 
Hardy). Но эти ошибки в логах вроде
перестали появляться после r109.
```

Original comment by `retratserif@gmail.com` on 3 Apr 2009 at 9:41

**Comment by GoogleCodeExporter** [comment]
```
неактуально
```

Original comment by `zdevel` on 30 Jun 2009 at 8:18

**Comment by GoogleCodeExporter** [comment]
Original comment by `tishka17` on 1 Jul 2009 at 6:48
- Changed state: **Invalid**
