### ISSUE TITLE
Не хочет логинится

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Oxyd76/pyvk-t#43]
```
2009-04-01 10:57:17+0000 [-] createThread x-demon@x-demon.org
2009-04-01 10:57:18+0000 [-] waiting for task
2009-04-01 10:57:18+0000 [-] updating status for x-demon@x-demon.org : Are 
you ready to lose it all?
2009-04-01 10:57:18+0000 [-] setstatus: cant find fields
2009-04-01 10:57:18+0000 [-] FIXME need page check
Логина при этом нет. Отключил ради интереса 
синх статуса.
2009-04-01 10:58:27+0000 [XmlStream,client] SELECT * FROM users WHERE 
jid='x-demon@x-demon.org'
2009-04-01 10:58:28+0000 [-] createThread x-demon@x-demon.org
2009-04-01 10:58:28+0000 [-] waiting for task

```

Original issue reported on code.google.com by `zdevel` on 1 Apr 2009 at 10:58

**Comment by GoogleCodeExporter** [comment]
```
а сие при logout.
2009-04-01 11:00:14+0000 [XmlStream,client] logout x-demon@asdfsadx-demon.org
2009-04-01 11:00:14+0000 [XmlStream,client] x-demon@dasfasdfx-demon.org: logout
2009-04-01 11:00:14+0000 [XmlStream,client] delThread 
x-demon@sadfasdfx-demon.org
2009-04-01 11:00:14+0000 [-] dummy
(мусор сам добавил)

```

Original comment by `zdevel` on 1 Apr 2009 at 11:00

**Comment by GoogleCodeExporter** [comment]
```
Отбой. Потупил немного, но потом заработал.
```

Original comment by `zdevel` on 1 Apr 2009 at 11:06

**Comment by GoogleCodeExporter** [comment]
```
Отбой отбою. После реконнекта намертво 
отказывается коннектится. Логи вон там ^^^
```

Original comment by `zdevel` on 1 Apr 2009 at 11:12

**Comment by GoogleCodeExporter** [comment]
```
У меня тоже почему-то через несколько часов 
запуска транспорта перестаёт логиниться.
Логи:
2009/04/01 19:48 +0400 [XmlStream,client] Unhandled Error
    Traceback (most recent call last):
      File "/usr/lib/python2.5/site-packages/twisted/python/log.py", line 48, in
callWithLogger
        return callWithContext({"system": lp}, func, *args, **kw)
      File "/usr/lib/python2.5/site-packages/twisted/python/log.py", line 33, in
callWithContext
        return context.call({ILogContext: newCtx}, func, *args, **kw)
      File "/usr/lib/python2.5/site-packages/twisted/python/context.py", line 59, in
callWithContext
        return self.currentContext().callWithContext(ctx, func, *args, **kw)
      File "/usr/lib/python2.5/site-packages/twisted/python/context.py", line 37, in
callWithContext
        return func(*args,**kw)
    --- <exception caught here> ---
      File "/usr/lib/python2.5/site-packages/twisted/internet/epollreactor.py", line
197, in _doReadOrWrite
        why = selectable.doRead()
      File "/usr/lib/python2.5/site-packages/twisted/internet/tcp.py", line 362, in doRead
        return self.protocol.dataReceived(data)
      File "/usr/lib/python2.5/site-packages/twisted/words/xish/xmlstream.py", line 72,
in dataReceived
        self.stream.parse(data)
      File "/usr/lib/python2.5/site-packages/twisted/words/xish/domish.py", line 730, in
parse
        self.parser.Parse(buffer)
      File "/usr/lib/python2.5/site-packages/twisted/words/xish/domish.py", line 771, in
_onEndElement
        self.ElementEvent(self.currElem)
      File "/usr/lib/python2.5/site-packages/twisted/words/xish/xmlstream.py", line 104,
in onElement
        self.dispatch(element)
      File "/usr/lib/python2.5/site-packages/twisted/words/xish/utility.py", line 233,
in dispatch
        callbacklist.callback(object)
      File "/usr/lib/python2.5/site-packages/twisted/words/xish/utility.py", line 37, in
callback
        methodwrapper(*args, **kwargs)
      File "/usr/lib/python2.5/site-packages/twisted/words/xish/utility.py", line 21, in
__call__
        self.method(*nargs, **nkwargs)
      File "/home/firestarter/Desktop/Files/New/Install/pyvk-t/pyvkt_new.py", line 183,
in onMessage

d=self.users[bjid].pool.defer(f=self.commands.onMsg,jid=msg["from"],text=cmd,v_i
d=v_id)
    exceptions.AttributeError: user instance has no attribute 'pool'

2009/04/01 19:48 +0400 [XmlStream,client] Unhandled error in Deferred:
2009/04/01 19:48 +0400 [XmlStream,client] Unhandled Error
    Traceback (most recent call last):
    Failure: twisted.internet.error.ConnectionLost: Connection to the other side was
lost in a non-clean fashion.

2009/04/01 19:48 +0400 [XmlStream,client] <twisted.internet.tcp.Connector 
instance at
0x83c012c> will retry in 2 seconds
2009/04/01 19:48 +0400 [XmlStream,client] Stopping factory
<twisted.words.protocols.jabber.xmlstream.XmlStreamFactory instance at 
0x85cec4c>

```

Original comment by `retratserif@gmail.com` on 1 Apr 2009 at 3:54

**Comment by GoogleCodeExporter** [comment]
```
первая проблема уже решена.
вторая может быть связана с тем же багом, 
проверьте, как будет в 108 ревизии
```

Original comment by `Equidamoid` on 1 Apr 2009 at 6:06
- Changed state: **Unconfirmed**

**Comment by GoogleCodeExporter** [comment]
```
неактуально
```

Original comment by `zdevel` on 30 Jun 2009 at 8:18

**Comment by GoogleCodeExporter** [comment]
Original comment by `Equidamoid` on 15 Nov 2009 at 12:39
- Changed state: **Fixed**
