### ISSUE TITLE
А коннект к бд то теряется!

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Oxyd76/pyvk-t#47]
```
БД на другом сервере. Может пинговать как 
нить или делать запрос какой 
нить инфы с бд, скажем, раз в 10 минут? 
(опционально)
2009-04-06 12:00:03+0000 [-] Unhandled Error
        Traceback (most recent call last):
          File "/usr/lib/python2.5/threading.py", line 446, in run
            self.__target(*self.__args, **self.__kwargs)
          File "/usr/lib/python2.5/site-packages/twisted/python/
threadpool.py", line 161, in _worker
            context.call(ctx, function, *args, **kwargs)
          File "/usr/lib/python2.5/site-packages/twisted/python/
context.py", line 59, in callWithContext
            return self.currentContext().callWithContext(ctx, func, *args, 
**kw)
          File "/usr/lib/python2.5/site-packages/twisted/python/
context.py", line 37, in callWithContext
            return func(*args,**kw)
        --- <exception caught here> ---
          File "/usr/lib/python2.5/site-packages/twisted/internet/
threads.py", line 24, in _putResultInDeferred
            result = f(*args, **kwargs)
          File "/usr/lib/python2.5/site-packages/twisted/enterprise/
adbapi.py", line 380, in _runInteraction
            conn.rollback()
          File "/usr/lib/python2.5/site-packages/twisted/enterprise/
adbapi.py", line 65, in rollback
            raise ConnectionLost()
        twisted.enterprise.adbapi.ConnectionLost:

```

Original issue reported on code.google.com by `zdevel` on 6 Apr 2009 at 12:08

**Comment by GoogleCodeExporter** [comment]
```
Мне подсознание говорит что коннект к БД не 
должен быть постоянным. Но почему он вот 
так вот теряется хз... Буду дальше думать.
```

Original comment by `tishka17` on 6 Apr 2009 at 12:32

**Comment by GoogleCodeExporter** [comment]
```
Создать пустую таблицу, скажем, ping, и 
запрашивать оттуда инфу каждые 30 мин =) Я в
php везде почти mysql_pconnect использую.
```

Original comment by `zdevel` on 10 Apr 2009 at 5:56

**Comment by GoogleCodeExporter** [comment]
```
Такая же фигня:
2009-04-11 19:36:34+0400 [XmlStream,client] adbapi closing: MySQLdb
2009-04-11 19:36:34+0400 [XmlStream,client] Connection lost.
2009-04-11 19:36:34+0400 [XmlStream,client] Unhandled error in Deferred:
2009-04-11 19:36:34+0400 [XmlStream,client] Unhandled Error
    Traceback (most recent call last):
      File "/usr/lib/python2.5/threading.py", line 446, in run
        self.__target(*self.__args, **self.__kwargs)
      File "/usr/lib/python2.5/site-packages/twisted/python/threadpool.py", line 161, in
_worker
        context.call(ctx, function, *args, **kwargs)
      File "/usr/lib/python2.5/site-packages/twisted/python/context.py", line 59, in
callWithContext
        return self.currentContext().callWithContext(ctx, func, *args, **kw)
      File "/usr/lib/python2.5/site-packages/twisted/python/context.py", line 37, in
callWithContext
        return func(*args,**kw)
    --- <exception caught here> ---
      File "/usr/lib/python2.5/site-packages/twisted/internet/threads.py", line 24, in
_putResultInDeferred
        result = f(*args, **kwargs)
      File "/usr/lib/python2.5/site-packages/twisted/enterprise/adbapi.py", line 380, in
_runInteraction
        conn.rollback()
      File "/usr/lib/python2.5/site-packages/twisted/enterprise/adbapi.py", line 65, in
rollback
        raise ConnectionLost()
    twisted.enterprise.adbapi.ConnectionLost: 

Я заметил что у меня такое происходит когда 
я авторизуюсь на одном клиенте, затем
чуть позже авторизуюсь на втором(первый 
при этом остаётся авторизованным). Затем 
если
статус второго установлю Offline, 
залогиниться уже невозможно на транспорте, 
причём
залогиниться не может ни один из аккаунтов 
транспорта.
MySQL на локальном хосте.

При попытках залогиниться в логе 
появляются ещё такие сообщения:
2009-04-11 09:34:01+0400 [XmlStream,client] Unhandled Error
    Traceback (most recent call last):
      File "/build/buildd/python2.5-2.5.2/Modules/pyexpat.c", line 656, in EndElement

      File "/usr/lib/python2.5/site-packages/twisted/words/xish/domish.py", line 780, in
_onEndElement
        self.ElementEvent(self.currElem)
      File "/usr/lib/python2.5/site-packages/twisted/words/xish/xmlstream.py", line 106,
in onElement
        self.dispatch(element)
      File "/usr/lib/python2.5/site-packages/twisted/words/xish/utility.py", line 316,
in dispatch
        callbacklist.callback(obj)
    --- <exception caught here> ---
      File "/usr/lib/python2.5/site-packages/twisted/words/xish/utility.py", line 106,
in callback
        methodwrapper(*args, **kwargs)
      File "/usr/lib/python2.5/site-packages/twisted/words/xish/utility.py", line 27, in
__call__
        self.method(*nargs, **nkwargs)
      File "/home/firestarter/Desktop/Files/New/Install/pyvk-t/pyvkt_new.py", line 771,
in onPresence
        self.delResource(prs["from"])
      File "/home/firestarter/Desktop/Files/New/Install/pyvk-t/pyvkt_new.py", line 762,
in delResource
        self.users[bjid].logout()
      File "/home/firestarter/Desktop/Files/New/Install/pyvk-t/pyvkt_user.py", line 293,
in logout
        mq="UPDATE users SET roster='%s', config='%s' WHERE
jid='%s';"%(b64encode(cPickle.dumps(self.roster)),b64encode(cPickle.dumps(self.c
onfig)),safe(self.bjid))
    exceptions.AttributeError: user instance has no attribute 'config'

2009-04-11 10:15:17+0400 [XmlStream,client] Unhandled Error
    Traceback (most recent call last):
      File "/build/buildd/python2.5-2.5.2/Modules/pyexpat.c", line 656, in EndElement

      File "/usr/lib/python2.5/site-packages/twisted/words/xish/domish.py", line 780, in
_onEndElement
        self.ElementEvent(self.currElem)
      File "/usr/lib/python2.5/site-packages/twisted/words/xish/xmlstream.py", line 106,
in onElement
        self.dispatch(element)
      File "/usr/lib/python2.5/site-packages/twisted/words/xish/utility.py", line 316,
in dispatch
        callbacklist.callback(obj)
    --- <exception caught here> ---
      File "/usr/lib/python2.5/site-packages/twisted/words/xish/utility.py", line 106,
in callback
        methodwrapper(*args, **kwargs)
      File "/usr/lib/python2.5/site-packages/twisted/words/xish/utility.py", line 27, in
__call__
        self.method(*nargs, **nkwargs)
      File "/home/firestarter/Desktop/Files/New/Install/pyvk-t/pyvkt_new.py", line 771,
in onPresence
        self.delResource(prs["from"])
      File "/home/firestarter/Desktop/Files/New/Install/pyvk-t/pyvkt_new.py", line 762,
in delResource
        self.users[bjid].logout()
      File "/home/firestarter/Desktop/Files/New/Install/pyvk-t/pyvkt_user.py", line 293,
in logout
        mq="UPDATE users SET roster='%s', config='%s' WHERE
jid='%s';"%(b64encode(cPickle.dumps(self.roster)),b64encode(cPickle.dumps(self.c
onfig)),safe(self.bjid))
    exceptions.AttributeError: user instance has no attribute 'config'

2009-04-11 10:15:29+0400 [-] resources:  
{u'firestarter@ubuntu-jabber.de/Bombus': None}
2009-04-11 13:46:19+0400 [XmlStream,client] Unhandled Error
    Traceback (most recent call last):
      File "/build/buildd/python2.5-2.5.2/Modules/pyexpat.c", line 656, in EndElement

      File "/usr/lib/python2.5/site-packages/twisted/words/xish/domish.py", line 780, in
_onEndElement
        self.ElementEvent(self.currElem)
      File "/usr/lib/python2.5/site-packages/twisted/words/xish/xmlstream.py", line 106,
in onElement
        self.dispatch(element)
      File "/usr/lib/python2.5/site-packages/twisted/words/xish/utility.py", line 316,
in dispatch
        callbacklist.callback(obj)
    --- <exception caught here> ---
      File "/usr/lib/python2.5/site-packages/twisted/words/xish/utility.py", line 106,
in callback
        methodwrapper(*args, **kwargs)
      File "/usr/lib/python2.5/site-packages/twisted/words/xish/utility.py", line 27, in
__call__
        self.method(*nargs, **nkwargs)
      File "/home/firestarter/Desktop/Files/New/Install/pyvk-t/pyvkt_new.py", line 771,
in onPresence
        self.delResource(prs["from"])
      File "/home/firestarter/Desktop/Files/New/Install/pyvk-t/pyvkt_new.py", line 762,
in delResource
        self.users[bjid].logout()
      File "/home/firestarter/Desktop/Files/New/Install/pyvk-t/pyvkt_user.py", line 293,
in logout
        mq="UPDATE users SET roster='%s', config='%s' WHERE
jid='%s';"%(b64encode(cPickle.dumps(self.roster)),b64encode(cPickle.dumps(self.c
onfig)),safe(self.bjid))
    exceptions.AttributeError: user instance has no attribute 'config'
```

Original comment by `retratserif@gmail.com` on 11 Apr 2009 at 3:47

**Comment by GoogleCodeExporter** [comment]
```
c введением xml неактуально
```

Original comment by `zdevel` on 30 Jun 2009 at 8:16

**Comment by GoogleCodeExporter** [comment]
Original comment by `tishka17` on 1 Jul 2009 at 6:41
- Changed state: **WontFix**
