### ISSUE TITLE
Перестал запускаться...

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Oxyd76/pyvk-t#58]
```
/home/firestarter/Desktop/Files/New/Install/pyvk-t/pyvkt_new.py:23:
DeprecationWarning: the sha module is deprecated; use the hashlib module
instead
  import sys,os,cPickle,sha
/var/lib/python-support/python2.6/MySQLdb/__init__.py:34:
DeprecationWarning: the sets module is deprecated
  from sets import ImmutableSet
Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/twisted/application/app.py", line
694, in run
    runApp(config)
  File "/usr/lib/python2.6/dist-packages/twisted/scripts/twistd.py", line
23, in runApp
    _SomeApplicationRunner(config).run()
  File "/usr/lib/python2.6/dist-packages/twisted/application/app.py", line
411, in run
    self.application = self.createOrGetApplication()
  File "/usr/lib/python2.6/dist-packages/twisted/application/app.py", line
494, in createOrGetApplication
    application = getApplication(self.config, passphrase)
--- <exception caught here> ---
  File "/usr/lib/python2.6/dist-packages/twisted/application/app.py", line
505, in getApplication
    application = service.loadApplication(filename, style, passphrase)
  File "/usr/lib/python2.6/dist-packages/twisted/application/service.py",
line 390, in loadApplication
    application = sob.loadValueFromFile(filename, 'application', passphrase)
  File "/usr/lib/python2.6/dist-packages/twisted/persisted/sob.py", line
215, in loadValueFromFile
    exec fileObj in d, d
  File "pyvkt_new.tac", line 30, in <module>
    s = pyvkt_new.pyvk_t()
  File "/home/firestarter/Desktop/Files/New/Install/pyvk-t/pyvkt_new.py",
line 143, in __init__
    self.pollMgr=pollManager(self)
  File
"/home/firestarter/Desktop/Files/New/Install/pyvk-t/pyvkt_spikes.py", line
81, in __init__
    self.daemon=True
  File "/usr/lib/python2.6/threading.py", line 684, in daemon
    raise RuntimeError("Thread.__init__() not called")
exceptions.RuntimeError: Thread.__init__() not called
Exception AttributeError: "type object 'Thread' has no attribute 'exit'" in
 ignored

Failed to load application: Thread.__init__() not called

```

Original issue reported on code.google.com by `retratserif@gmail.com` on 1 May 2009 at 2:50

**Comment by GoogleCodeExporter** [comment]
```
Отбой, проблема заключалась в том что на 
Jaunty, до которого я недавно обновился, по
умолчанию используется Python 2.6 , и код 
транспорта оказался с ним несовместим.
Запустил как python2.5 /usr/bin/twistd -y
"/home/firestarter/Desktop/Install/pyvk-t/pyvkt_new.tac" -l
"/home/firestarter/Desktop/Install/pyvk-t/pyvkt.log"

```

Original comment by `retratserif@gmail.com` on 5 May 2009 at 8:02

**Comment by GoogleCodeExporter** [comment]
```
теперь совместим
```

Original comment by `Equidamoid` on 16 Oct 2009 at 3:17
- Changed state: **Fixed**
