### ISSUE TITLE
Как побороть? SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Oxyd76/pyvk-t#61]
```
вот такая ошибка при старте :( 
# python pyvkt_new.py
Traceback (most recent call last):
  File "pyvkt_new.py", line 39, in ?
    from libvkontakte import *
  File "/opt/ejabberd/transport/pyvk/libvkontakte.py", line 82
    class vkonThread():
                     ^
SyntaxError: invalid syntax

```

Original issue reported on code.google.com by `skaramanga86` on 25 May 2009 at 7:08

**Comment by GoogleCodeExporter** [comment]
```
разобрались как запускать?
```

Original comment by `tishka17` on 26 May 2009 at 5:37
- Changed state: **Unconfirmed**

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
спасибо  tishka17
Проблема была в питоне, как выяснилось на 
python2.4 данный транспорт не работает...
думаю это где то нужно отметить, так как 
когда я ставил транспорт о версии питона
ничего не было сказанно... Сейчас только 
нашёл упоминания о версии питона в Вики,
может лучше на основной странице написать 
что требуется для работы транспорта? :)

```

Original comment by `skaramanga86` on 27 May 2009 at 4:37

**Comment by GoogleCodeExporter** [comment]
Original comment by `tishka17` on 27 May 2009 at 12:38
- Changed state: **Invalid**

**Comment by GoogleCodeExporter** [comment]
```
Issue 70 has been merged into this issue.
```

Original comment by `tishka17` on 1 Oct 2009 at 9:43
