### ISSUE TITLE
Последний checkout , ошибка при запуске

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Oxyd76/pyvk-t#64]
```
twistd -y pyvkt_new.tac

-----------
you have to set features/datadir in your config file and convert yur DB to
new format using #convertdb command
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/twisted/application/app.py", line
614, in run
    runApp(config)
  File "/usr/lib/python2.5/site-packages/twisted/scripts/twistd.py", line
23, in runApp
    _SomeApplicationRunner(config).run()
  File "/usr/lib/python2.5/site-packages/twisted/application/app.py", line
330, in run
    self.application = self.createOrGetApplication()
  File "/usr/lib/python2.5/site-packages/twisted/application/app.py", line
416, in createOrGetApplication
    application = getApplication(self.config, passphrase)
--- <exception caught here> ---
  File "/usr/lib/python2.5/site-packages/twisted/application/app.py", line
427, in getApplication
    application = service.loadApplication(filename, style, passphrase)
  File "/usr/lib/python2.5/site-packages/twisted/application/service.py",
line 368, in loadApplication
    application = sob.loadValueFromFile(filename, 'application', passphrase)
  File "/usr/lib/python2.5/site-packages/twisted/persisted/sob.py", line
214, in loadValueFromFile
    exec fileObj in d, d
  File "pyvkt_new.tac", line 31, in <module>
    s = pyvkt_new.pyvk_t()
  File "/opt/vk/pyvkt_new.py", line 139, in __init__
    raise Exception
exceptions.Exception: 
stopping service...
stopping transport...
stopping poolMgr...
Exception exceptions.AttributeError: "pyvk_t instance has no attribute
'pollMgr'" in <bound method pyvk_t.__del__ of <pyvkt_new.pyvk_t instance at
0x3196bd8>> ignored

Failed to load application: 

----------


конфиг


-----------
[general]
transport_jid: vk.xxxxxxxx
server: xxxxxxxxxxx
secret: xxxxxxxxxxxx
port: 5559
admin: nickname@xxxxxxxxxxx

[database]
module: MySQLdb
host: localhost
user: pyvk
passwd: xxxxxxxx
db: db_pyvk

[features]
avatars: true
sync_status: true
cache_path: /opt/vk/cache
roster_management: true
feed_notify: true
cookies_path: /opt/vk/cookies
resolve_links: true

[debug]
dump_path: /opt/vk/dumps
-----------
```

Original issue reported on code.google.com by `martianv...@gmail.com` on 17 Jun 2009 at 12:08

**Comment by GoogleCodeExporter** [comment]
```
http://vkontakte.ru/pages.php?o=-7658304&p=mysql2xml
```

Original comment by `hart...@gmail.com` on 17 Jun 2009 at 3:01

**Comment by GoogleCodeExporter** [comment]
Original comment by `tishka17` on 30 Jun 2009 at 5:41
- Changed state: **WontFix**
