### ISSUE TITLE
Не запускается - cannot import name randbytes

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Oxyd76/pyvk-t#70]
```
ОС - freebsd 6.4

twistd -y pyvkt_new.tac -n
2009/09/28 11:38 +0000 [-] Log opened.
2009/09/28 11:38 +0000 [-] twistd 2.5.0 (/usr/local/bin/python2.4 2.4.3) 
starting up
2009/09/28 11:38 +0000 [-] reactor class: <class 
'twisted.internet.selectreactor.SelectReactor'>
2009/09/28 11:38 +0000 [-] Loading pyvkt_new.tac...
2009/09/28 11:38 +0000 [-] Traceback (most recent call last):
2009/09/28 11:38 +0000 [-]   File "/usr/local/lib/python2.4/site-packages/
twisted/application/app.py", line 218, in getApplication
2009/09/28 11:38 +0000 [-]     application = service.loadApplication
(filename, style, passphrase)
2009/09/28 11:38 +0000 [-]   File "/usr/local/lib/python2.4/site-packages/
twisted/application/service.py", line 341, in loadApplication
2009/09/28 11:38 +0000 [-]     application = sob.loadValueFromFile
(filename, 'application', passphrase)
2009/09/28 11:38 +0000 [-]   File "/usr/local/lib/python2.4/site-packages/
twisted/persisted/sob.py", line 215, in loadValueFromFile
2009/09/28 11:38 +0000 [-]     exec fileObj in d, d
2009/09/28 11:38 +0000 [-]   File "pyvkt_new.tac", line 4, in ?
2009/09/28 11:38 +0000 [-]     from twisted.words.protocols.jabber import 
component
2009/09/28 11:38 +0000 [-]   File "/usr/local/lib/python2.4/site-packages/
twisted/words/protocols/jabber/component.py", line 27, in ?
2009/09/28 11:38 +0000 [-]     from twisted.words.protocols.jabber import 
error, ijabber, jstrports, xmlstream
2009/09/28 11:38 +0000 [-]   File "/usr/local/lib/python2.4/site-packages/
twisted/words/protocols/jabber/xmlstream.py", line 18, in ?
2009/09/28 11:38 +0000 [-]     from twisted.python import failure, log, 
randbytes
2009/09/28 11:38 +0000 [-] ImportError: cannot import name randbytes
2009/09/28 11:38 +0000 [-] Failed to load application: cannot import name 
randbytes
2009/09/28 11:38 +0000 [-] Unhandled Error
        Traceback (most recent call last):
          File "/usr/local/lib/python2.4/site-packages/twisted/application/
app.py", line 379, in run
            runApp(config)
          File "/usr/local/lib/python2.4/site-packages/twisted/scripts/
twistd.py", line 23, in runApp
            _SomeApplicationRunner(config).run()
          File "/usr/local/lib/python2.4/site-packages/twisted/application/
app.py", line 157, in run
            self.application = self.createOrGetApplication()
          File "/usr/local/lib/python2.4/site-packages/twisted/application/
app.py", line 207, in createOrGetApplication
            application = getApplication(self.config, passphrase)
        --- <exception caught here> ---
          File "/usr/local/lib/python2.4/site-packages/twisted/application/
app.py", line 218, in getApplication
            application = service.loadApplication(filename, style, 
passphrase)
          File "/usr/local/lib/python2.4/site-packages/twisted/application/
service.py", line 341, in loadApplication
            application = sob.loadValueFromFile(filename, 'application', 
passphrase)
          File "/usr/local/lib/python2.4/site-packages/twisted/persisted/
sob.py", line 215, in loadValueFromFile
            exec fileObj in d, d
          File "pyvkt_new.tac", line 4, in ?
            from twisted.words.protocols.jabber import component
          File "/usr/local/lib/python2.4/site-packages/twisted/words/
protocols/jabber/component.py", line 27, in ?
            from twisted.words.protocols.jabber import error, ijabber, 
jstrports, xmlstream
          File "/usr/local/lib/python2.4/site-packages/twisted/words/
protocols/jabber/xmlstream.py", line 18, in ?
            from twisted.python import failure, log, randbytes
        exceptions.ImportError: cannot import name randbytes


Failed to load application: cannot import name randbytes
2009/09/28 11:38 +0000 [-]
```

Original issue reported on code.google.com by `lord.d...@gmail.com` on 28 Sep 2009 at 11:41

**Comment by GoogleCodeExporter** [comment]
```
Попробуйте твистед до 8й ветки обновить
```

Original comment by `tishka17` on 29 Sep 2009 at 2:03

**Comment by GoogleCodeExporter** [comment]
```
Обновил.
Далее:

twistd -y pyvkt_new.tac -n
Traceback (most recent call last):
  File "/usr/local/lib/python2.4/site-packages/twisted/application/app.py", line 
694, in run
    runApp(config)
  File "/usr/local/lib/python2.4/site-packages/twisted/scripts/twistd.py", line 23, 
in runApp
    _SomeApplicationRunner(config).run()
  File "/usr/local/lib/python2.4/site-packages/twisted/application/app.py", line 
411, in run
    self.application = self.createOrGetApplication()
  File "/usr/local/lib/python2.4/site-packages/twisted/application/app.py", line 
494, in createOrGetApplication
    application = getApplication(self.config, passphrase)
--- <exception caught here> ---
  File "/usr/local/lib/python2.4/site-packages/twisted/application/app.py", line 
505, in getApplication
    application = service.loadApplication(filename, style, passphrase)
  File "/usr/local/lib/python2.4/site-packages/twisted/application/service.py", line 
390, in loadApplication
    application = sob.loadValueFromFile(filename, 'application', passphrase)
  File "/usr/local/lib/python2.4/site-packages/twisted/persisted/sob.py", line 214, 
in loadValueFromFile
    exec fileObj in d, d
  File "pyvkt_new.tac", line 6, in ?
    import pyvkt_new
  File "/root/pyvk-t-read-only/pyvkt_new.py", line 39, in ?
    from pyvkt_user import user
  File "/root/pyvk-t-read-only/pyvkt_user.py", line 23, in ?
    import libvkontakte
exceptions.SyntaxError: invalid syntax (libvkontakte.py, line 72)

Failed to load application: invalid syntax (libvkontakte.py, line 72)
```

Original comment by `lord.d...@gmail.com` on 1 Oct 2009 at 8:54

**Comment by GoogleCodeExporter** [comment]
Original comment by `tishka17` on 1 Oct 2009 at 9:43
- Changed state: **Duplicate**
