### ISSUE TITLE
Невозможно получить список комманд

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Oxyd76/pyvk-t#76]
```
Использую notwisted версию, пришлось немножко 
доделать, чтобы работала, 
короче стартует, все норм, соединяется, 
выдает себя в списке сервисов 
сервера, а когда дело доходит до получения 
информации и списка комманд, 
ничего не выходит, а в консоли идет 
следующее:

  *  2009-10-28 16:03:24,000 [CRITICAL] stream error
Traceback (most recent call last):
  File "E:\Install\pyvk-t\notwisted\pyvkt\comstream.py", line 93, in 
recvLoop
    s=self.getPacket()
  File "E:\Install\pyvk-t\notwisted\pyvkt\comstream.py", line 72, in 
getPacket
    c=self.sock.recv(1)
error: [Errno 10054]

  *  2009-10-28 16:03:25,015 [ERROR] queue error
Traceback (most recent call last):
  File "E:\Install\pyvk-t\notwisted\pyvkt\comstream.py", line 99, in 
recvLoop
    self.recvQueue.put(etree.fromstring(s))
  File "lxml.etree.pyx", line 2538, in lxml.etree.fromstring (src/lxml/
lxml.etre
e.c:48266)
  File "parser.pxi", line 1533, in lxml.etree._parseMemoryDocument (src/
lxml/lxm
l.etree.c:71615)
ValueError: can only parse strings

...и так далее в том же духе по циклу(( В чем 
дело?
```

Original issue reported on code.google.com by `rreverser` on 28 Oct 2009 at 2:16

**Comment by GoogleCodeExporter** [comment]
```
Могу посоветовать запуск с ключём --debug и 
смотреть что выводится: какие пакеты
получаем и какие отправляем.

У меня были проблемы похожие. Фикс запостил 
тут:
http://code.google.com/p/pyvk-t/issues/detail?id=71#c9
```

Original comment by `mro...@gmail.com` on 28 Oct 2009 at 3:24

**Comment by GoogleCodeExporter** [comment]
```
Это и есть с --debug - сначала "общается" 
нормально с самим собой через сервак, а 
когда... (см. выше). Исправления не помогли 
(насколько я понимаю, они в данном 
случае ничего и не должны были делать, так 
как только изменяют названия xml-узлов, и 
до ошибок подключения никакого отношения 
не имеют).
```

Original comment by `rreverser` on 28 Oct 2009 at 3:53

**Comment by GoogleCodeExporter** [comment]
```
Смотрите сами. Я лишь предложил вариант.
Вариант делать тестовый вывод, где, 
вероятно, может быть ошибка. Я так дошёл до
истины. :)
```

Original comment by `mro...@gmail.com` on 28 Oct 2009 at 5:16

**Comment by GoogleCodeExporter** [comment]
```
А есть у кого полностью работоспособный 
вариант?
```

Original comment by `rreverser` on 28 Oct 2009 at 5:23

**Comment by GoogleCodeExporter** [comment]
```
Заходите в pyvk-t@conference.jabber.ru там вводите online и 
увидите у скольких людей
полностью работоспособный вариант. :)
```

Original comment by `mro...@gmail.com` on 28 Oct 2009 at 6:58

**Comment by GoogleCodeExporter** [comment]
```
Да не в том смысле :)
Я тоже через работоспособный сижу, но 
захотелось свой сервак поднять, вот я и 
спрашиваю, может ли кто-нить выложить уже 
готовый работоспособный вариант 
(желательно notwisted, но как получится)?
```

Original comment by `rreverser` on 28 Oct 2009 at 7:18

**Comment by GoogleCodeExporter** [comment]
```
Здесь еще кто-то читает?
```

Original comment by `rreverser` on 29 Oct 2009 at 7:52

**Comment by GoogleCodeExporter** [comment]
```
а какой джаббер-серв стоит?
```

Original comment by `Equidamoid` on 30 Oct 2009 at 10:12

**Comment by GoogleCodeExporter** [comment]
```
ejabberd
```

Original comment by `rreverser` on 30 Oct 2009 at 10:21

**Comment by GoogleCodeExporter** [comment]
```
В 174 ревизии будет более корректное 
переподключение к серву. Возможно, 
проблема решится
```

Original comment by `Equidamoid` on 15 Nov 2009 at 12:26
- Changed state: **Started**

**Comment by GoogleCodeExporter** [comment]
```
Но у дргих же как-то и с этой ревизией 
серверы работают...
```

Original comment by `rreverser` on 18 Nov 2009 at 12:16

**Comment by GoogleCodeExporter** [comment]
```
мне бы полный лог обмена данными между 
транспортом и сервом...
```

Original comment by `Equidamoid` on 18 Nov 2009 at 2:53
