### ISSUE TITLE
Падение при таймауте открытия страницы

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Oxyd76/pyvk-t#8]
```
Судя по всему транспорт так и не смог 
загрузить страницу с сайта...
И упал...


test.xml:174: warning: xmlns: URI vcard-temp is not absolute              


Card xmlns='vcard-temp' version='2.0' prodid='-//HandGen//NONSGML vGen
v1.0//EN'                                                                 


    ^                                                                     

OUT: '</stream:stream>'                                                   


Traceback (most recent call last):                                        


  File "./pyvk-t.py", line 356, in <module>                               


    tr.loop(1)                                                            


  File
"/usr/local/lib/python2.5/site-packages/pyxmpp/jabberd/component.py", line
189, in loop                                                               
    self.stream.loop(timeout)                                             


  File "/usr/local/lib/python2.5/site-packages/pyxmpp/streambase.py", line
588, in loop
    act=self._loop_iter(timeout)
  File "/usr/local/lib/python2.5/site-packages/pyxmpp/streambase.py", line
616, in _loop_iter
    self._process()
  File "/usr/local/lib/python2.5/site-packages/pyxmpp/streamtls.py", line
179, in _process
    StreamBase._process(self)
  File "/usr/local/lib/python2.5/site-packages/pyxmpp/streambase.py", line
645, in _process
    raise FatalStreamError("IO Error: "+str(e))
pyxmpp.exceptions.FatalStreamError: IO Error: <urlopen error (60,
'Operation timed out')>
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python2.5/threading.py", line 486, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.5/threading.py", line 446, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/jabber/pyvk-t-read-only/libvkontakte.py", line 280, in loop
    tonline=self.getOnlineList()
  File "/home/jabber/pyvk-t-read-only/libvkontakte.py", line 72, in
getOnlineList
    res=self.opener.open(req)
  File "/usr/local/lib/python2.5/urllib2.py", line 381, in open
    response = self._open(req, data)
  File "/usr/local/lib/python2.5/urllib2.py", line 399, in _open
    '_open', req)
  File "/usr/local/lib/python2.5/urllib2.py", line 360, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.5/urllib2.py", line 1107, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/local/lib/python2.5/urllib2.py", line 1082, in do_open
    raise URLError(err)
URLError: <urlopen error (60, 'Operation timed out')>

```

Original issue reported on code.google.com by `hart...@gmail.com` on 23 Feb 2009 at 9:53

**Comment by GoogleCodeExporter** [comment]
```
Проблема ясна, вечером поправлю
```

Original comment by `Equidamoid` on 24 Feb 2009 at 5:31
- Changed state: **Accepted**
- Added labels: **Priority-High**
- Removed labels: **Priority-Medium**

**Comment by GoogleCodeExporter** [comment]
```
сделал
```

Original comment by `Equidamoid` on 24 Feb 2009 at 5:35
- Changed state: **Fixed**
