### ISSUE TITLE
не стартует 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Oxyd76/pyvk-t#90]
```
./main.py
{'debug': {'dump_path': u'dumps'}, 'storage': {'datadir': u'./data', 
'cache': u'./cache', 'cookies': u'./cookies'}, 'workarounds': 
{'fix_namespaces': False}, 'features': {'status': '', 'sync_status': True, 
'avatars': True}, 'general': {'jid': u'vkontakte.staynet.ru', 'admin': 
u'vpupkin@localhost', 'service_name': u'Vkontakte Gateway', 'server': u'ля 
ляля.ru', 'secret': u'password', 'port': 5275}}
Traceback (most recent call last):
  File "./main.py", line 46, in <module>
    if not s.connect(conf.get("general","server"),conf.get
("general","port"),conf.get("general","secret")):
  File "/usr/local/etc/kontakt/pyvkt/comstream.py", line 101, in connect
    sock=connect_socket((host,port))
  File "/usr/local/etc/kontakt/pyvkt/comstream.py", line 70, in 
connect_socket
    raise socket.error, msg
socket.error: (61, 'Connection refused')
на этом порту висит еще и mrim.возможно 
работа транспортов на одном порту 
или все разные?OC FreeBSD версия 192

```

Original issue reported on code.google.com by `hakkma...@gmail.com` on 31 Jan 2010 at 1:35

**Comment by GoogleCodeExporter** [comment]
```
включил дебаг
python main.py
{'debug': {'dump_path': u'dumps'}, 'storage': {'datadir': u'./data', 'cache': 
u'./
cache', 'cookies': u'./cookies'}, 'workarounds': {'fix_namespaces': False}, 
'features': {'status': '', 'sync_status': True, 'avatars': True}, 'general': 
{'jid': 
u'vkontakte.staynet.ru', 'admin': None, 'service_name': 
u'\u0412\u043a\u043e\u043d
\u0442\u0430\u043a\u0442\u0435.\u0440\u0443 \u0442\u0440\u0430\u043d\u0441\u043f
\u043e\u0440\u0442', 'server': u'localhost', 'secret': u'xxxxxx', 'port': 5275}}
  *  2010-01-31 18:41:38,660 [CRI] <module>[MainThread]: can't connect
та же песня...чего не хватает?может модуля 
какого нибудь?

```

Original comment by `hakkma...@gmail.com` on 31 Jan 2010 at 3:43

**Comment by GoogleCodeExporter** [comment]
```
надо лог обмена данными с сервом.
во фре strace есть? ну, или сниффером каким-нить
```

Original comment by `Equidamoid` on 1 Feb 2010 at 7:43
